config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { registrations: 'registrations' }
  if Rails.env.test?
    root 'blogs#index'
  else
    root 'blogs#show', id: Blog.last.id
  end

  get 'about'     =>  'static_pages#about'
  get 'contact'   =>  'contacts#new'
  post 'contact'  =>  'contacts#create'

  resources :blogs do
    resources :comments, :only => [:create]
  end
  resources :categories, only: [:show, :index]
  resources :comments, only: [:destroy]
  resources :songs, only: [:index, :create, :destroy]

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	is_impressionable
	belongs_to :user
	#
	has_many :posts, dependent: :destroy, inverse_of: :blog
	has_many :comments, dependent: :destroy
	has_many :categorizations, dependent: :destroy
  	has_many :categories, :through => :categorizations, :class_name => 'Category'
  	#
  	accepts_nested_attributes_for :categories
  	accepts_nested_attributes_for :categorizations
  	accepts_nested_attributes_for :posts, allow_destroy: true, limit: 5, reject_if: proc { |attributes| attributes['content'].blank? }
  	#
	validates_associated :posts
	validates :title, presence: true, length: { maximum: 55, minimum: 5 }
	validates :sub_title, length: { maximum: 55 }, allow_blank: true
	validates :tags, presence: true,  length: { maximum: 120, minimum: 5 }
	validates :posts, presence: true
	validates :user, presence: true
	validates :categorizations, presence: true
	
	def unique_views
		impressionist_count(:filter=>:ip_address)
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include BlogsHelper

  impressionist :actions => [:show]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @blogs = Blog.all
  end

  def show
    @comments = @blog.comments.order_all
    @songs = Song.all.order('created_at desc')
  end

  def new
    @blog = Blog.new
    # Only build on new and invalid
    @blog.posts.build && @blog.categorizations.build unless performed?
  end

  def edit
  end

  def create
    @blog = current_user.blogs.new(blog_params)
      if (preview_button? && @blog.valid?)
        render :new
      elsif @blog.save
        User.all_except(current_user).each do |u| 
          BlogMailer.new_blog(u, @blog).deliver_now
        end
        # Extract into method, write test for this!
        redirect_to @blog, notice: 'Blog was successfully created.'
      else
        clear_preview_button
        render :new
      end
  end

  def update
      if (preview_button? && @blog.valid?)
        @blog.assign_attributes(blog_params)
        render :edit
       elsif @blog.update(blog_params)
        redirect_to @blog, notice: 'Blog was successfully updated.'
       else
        clear_preview_button
        render :edit
      end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
       params.require(:blog).permit(:title, :sub_title, :tags, :user_id, posts_attributes: [:id, :blog_id, :content, :_destroy],
                      categorizations_attributes: [:id, :_destroy, :category_id, category_attributes: [:id, :_destroy, :name]])
    end


end

app/helpers/blogs_helper.rb
module BlogsHelper

	def preview_button?
		params[:preview_button].present?
	end

	def clear_preview_button
		params.delete :preview_button
	end

	def pluralize_to_s(count, word)
		cnt = count
		pluralized = word.pluralize(cnt)
		"#{cnt} #{pluralized}"
	end

	def users_blog?(blog)
		current_user.id == blog.user_id rescue false
	end
	
end

app/views/blogs/_blog.html.erb
<h1><%= @blog.title %></h1>
<h3 class="center"><%= @blog.sub_title %></h3>
<h2>Posted on <%= @blog.created_at.to_formatted_s(:long_ordinal) unless @blog.created_at.nil? %> by
	<%= @blog.user.first_name %> <%= @blog.user.last_name %> (<%= pluralize(@blog.unique_views , "View") %>)
</h2>
<div class="col-md-10 col-md-offset-1">
	<div class="well bs-component">
		<% @blog.posts.each do |post| %>	
		    		<%= post.content.html_safe %>
		<% end %>
	</div>
</div>

app/views/blogs/_categorization_fields.html.erb
<div class='nested-fields categorization-fields'>
	<div class="category_from_list">
		<%= f.association :category,  collection: Category.all %>
	</div>
		<%= link_to_add_association "Insert New Category", f, :category, class: "add-tag btn btn-default" %>
		<%= link_to_remove_association "Remove", f, class: "remove-tag btn btn-default" %>
</div>	

app/views/blogs/_category_fields.html.erb
<div class="nested-fields">
	<%= f.input :name, :placeholder => 'New Category'  %>
</div>

app/views/blogs/_form.html.erb
<%= simple_form_for(@blog) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.input :title, placeholder: "The post title" %>

  <%= f.input :sub_title, placeholder: "The post sub title (song title usually)" %>

  <div id="categories">
      <%= f.simple_fields_for :categorizations do |categorization| %>
        <%= render 'categorization_fields', f: categorization %>
       <% end %>
        <%= link_to_add_association 'Add Blog Category', f, :categorizations, class: "btn btn-default" %>
  </div>

  <%= f.input :tags, placeholder: "Use to have as meta tags e.g Rock Roll Rocker" %>

  <div id='posts'>
      <%= f.simple_fields_for :posts do |post| %>
        <%= render 'post_fields', f: post %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association 'Add Post Section', f, :posts, class: "btn btn-info" %>
      </div>
  </div>

</br>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <%= f.submit "Preview", class: "btn btn-primary", name: "preview_button" %>
  <%= link_to 'Back', blogs_path , class: "btn btn-default" %>  
<% end %>

app/views/blogs/_index.html.erb
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Title</th>
      <th>Sub Title</th>
      <th>Posted At<th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
    <tr class="active">
      <td><%= blog.title %></td>
      <td><%= blog.sub_title %></td>
      <td><%= blog.created_at.to_date %></td>
      <td> by <%= blog.user.full_name %></td>
      <td>
        <%= link_to 'Read', blog, class: "btn btn-primary" %>
      <% if users_blog?(blog) %>
        <%= link_to 'Edit', edit_blog_path(blog), class: "btn btn-warning" %>
        <%= link_to 'Delete', blog, class: 'btn btn-danger',
            method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/blogs/_post_fields.html.erb
<div class='nested-fields'>
    <%= f.label :content %>
    <%= f.cktext_area :content, rows: 20 %>
    <%= link_to_remove_association "Remove Post", f, class: "btn btn-info" %>
</div>
</br>

app/views/blogs/_show.html.erb
<h1><%= @blog.title %></h1>
<h3 class="center"><%= @blog.sub_title %></h3>
<h2>Posted on <%= @blog.created_at.to_formatted_s(:long_ordinal) unless @blog.created_at.nil? %> by
	<%= @blog.user.first_name %> <%= @blog.user.last_name %>
</h2>
<div class="col-md-10 col-md-offset-1">
	<div class="well bs-component">
		<% @blog.posts.each do |post| %>	
		    		<%= post.content.html_safe %>
		<% end %>
	</div>
	
	<%= link_to 'Blogs', blogs_path, class: "btn btn-primary" if !preview_button? || logged_in? %>
	<%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-danger" if !preview_button? && users_blog(@blog) %>
</div>

app/views/blogs/edit.html.erb
<% provide(:title, 'Edit blog') %>
<% provide(:button_text, "Edit") %>
<div class="row">
	<%= render 'blog' if preview_button? %>
	<div class="col-md-8 col-md-offset-2">
		<h1 class="center">Edit Blog </h1>
		<div class="well bs-component">
			<%= render 'form' %>
		</div>	
	</div>
</div>

app/views/blogs/index.html.erb
<% provide(:title, "Blogs" )%>
<h1>Blogs</h1>
<div class="bs-component">
  <div class="col-md-10 col-md-offset-1">
    <%= render 'index' %>
       <% if admin_user? %>
       	  <%= link_to 'New Blog', new_blog_path, class: "btn btn-primary" %>
       <% end %>
    </div>
</div>

app/views/blogs/new.html.erb
<% provide(:title, 'New Blog') %>
<% provide(:button_text, "Create Blog") %>
<div class="row">
	<%= render 'blog' if preview_button? %>
	<div class="col-md-8 col-md-offset-2">
		<h1 class="center">Create a new blog</h1>
		<div class="well bs-component">
			<%= render 'form' %>	
		</div>	
	</div>
</div>

app/views/blogs/show.html.erb
<% provide(:title, @blog.title) %>
<% provide(:description, @blog.tags) %>
<div class="row">
		<%= render @blog %>	
	<div class="col-md-4 col-md-offset-1">
		<div class="well bs-component">
			<section id="comments_section">
				<% if current_user %>
					<%= render 'comments/new' %>
				<% else %>
					<%= link_to(content_tag(:h4, "Please Login to Comment"), new_user_session_path) %>
					<%= link_to(content_tag(:h4, "Sign Up to Comment"), new_user_registration_path) %>
				<% end %>
			</section>
		</div>
	</div>
	<div class="col-md-5 col-md-offset-1">
		<div class="well bs-component">
			<%= render 'comments/show' %>
		</div>
	</div>
	<div class="col-md-10 col-md-offset-1">
	  <% if @songs.any? %>
	    <div class="well bs-component">
	  	  <h3 class="center">Stock Rocker Songs</h3>
	      <%= render 'songs/show' %>
	    </div>
	  <% end %>
    </div>
</div>