config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { registrations: 'registrations' }
  if Rails.env.test?
    root 'blogs#index'
  else
    root 'blogs#show', id: Blog.last.id
  end

  get 'about'     =>  'static_pages#about'
  get 'contact'   =>  'contacts#new'
  post 'contact'  =>  'contacts#create'

  resources :blogs do
    resources :comments, :only => [:create]
  end
  resources :categories, only: [:show, :index]
  resources :comments, only: [:destroy]
  resources :songs, only: [:index, :create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="container">
	<div class="row">
		<section class="col-sm-4">
			<%= link_to image_tag("rails_logo.jpg", alt: "Rails logo", size: "80x70",class: "img-rounded"),
			 						'http://rubyonrails.org/' %>
		</section>
	</div>
	<div class="row">
		<p class="text-left">Copyright &copy; 2013 - <%= Time.now.year %> Stock Rocker</p>
	</div>
</footer>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78425999-1', 'auto');
  ga('send', 'pageview');

</script>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Stock Rocker', root_path, id: 'logo' %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav pull-right">
          <%= render 'layouts/navigation_links' %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
	<%= link_to 'About', about_path %>
</li>
<% if user_signed_in? %>
	<li>
		<%= link_to 'Blogs', blogs_path %>
	</li>
	<li>
		<%= link_to "Your User", edit_user_registration_path %>
	</li>
	<li>
		<%= link_to 'Logout', destroy_user_session_path, method: :delete  %>
	</li>
	<li>
		<%= link_to 'Songs', songs_path if admin_user? %>
	</li>
<% else %>
	<li>
		<%= link_to 'Categories', categories_path %>
	</li>
	<li>
		<%= link_to 'Contact', contact_path %>
	</li>
	<li>
		<%= link_to 'Login', new_user_session_path %>
	</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Stock Rocker Rock 'n' Roll Life Blog" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/google_analytics' %>
  </head>
  <body>
      <%= render 'layouts/header' %>
    <div class="container main">
         <%= render 'layouts/messages' %>
         <%= yield %>
    </div>
    <div class="container">
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>